"""
eval_genomes: the NEAT callback executed once per generation.
All shared state (screen, track, renderer, checkpoints) is passed in
via a closure constructed in main.py.
"""

import sys
import pygame
import neat

from src.car import Car

# Generation time-limit: ~20 seconds at 60 FPS
MAX_FRAMES = 1200

# Bonus fitness awarded each time a car passes a checkpoint
CHECKPOINT_BONUS = 200.0

# Starting position and heading (set to sit on the right straight of the oval)
START_X     = 1015   # right-side straight, midpoint between inner and outer ellipse
START_Y     = 400
START_ANGLE = 90     # degrees — facing upward (north on screen)


# ---------------------------------------------------------------------------
# Checkpoints
# Each entry is (cx, cy, radius).  Place them clockwise around the track
# centreline so the sim can verify forward progress.
# The values below match the ellipse track generated by generate_assets.py
# (cx=600, cy=400, rx=415, ry=275).
# ---------------------------------------------------------------------------

import math

def _make_checkpoints(n: int = 16) -> list[tuple[int, int, int]]:
    cx, cy, rx, ry = 600, 400, 415, 275
    pts = []
    for i in range(n):
        a = math.radians(360 * i / n)
        x = int(cx + rx * math.cos(a))
        y = int(cy - ry * math.sin(a))   # screen y inverted
        pts.append((x, y, 55))
    return pts

CHECKPOINTS = _make_checkpoints(16)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _handle_events(renderer) -> None:
    """Process pygame events; returns normally or calls sys.exit()."""
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_d:
                renderer.debug_rays = not renderer.debug_rays


def _check_checkpoints(car: Car, genome: neat.DefaultGenome) -> None:
    """Award bonus fitness when the car enters the next checkpoint circle."""
    if car.next_checkpoint >= len(CHECKPOINTS):
        return
    cx, cy, r = CHECKPOINTS[car.next_checkpoint]
    dist = car.position.distance_to((cx, cy))
    if dist < r:
        genome.fitness += CHECKPOINT_BONUS
        car.next_checkpoint += 1


# ---------------------------------------------------------------------------
# eval_genomes factory
# ---------------------------------------------------------------------------

def make_eval_genomes(screen: pygame.Surface, track, renderer, clock: pygame.time.Clock):
    """
    Return the eval_genomes function with the shared pygame objects closed over.
    Call this once in main.py and pass the result to population.run().
    """
    generation_counter = [0]
    best_fitness_ever  = [0.0]

    def eval_genomes(genomes, config):
        generation_counter[0] += 1
        gen = generation_counter[0]

        # --- Build nets + cars ---
        nets, cars, genome_list = [], [], []
        for genome_id, genome in genomes:
            genome.fitness = 0.0
            nets.append(neat.nn.FeedForwardNetwork.create(genome, config))
            cars.append(Car(START_X, START_Y, START_ANGLE))
            genome_list.append(genome)

        frame = 0
        clock_tick = clock.tick

        while True:
            _handle_events(renderer)

            # --- Update every living car ---
            all_dead = True
            for i, car in enumerate(cars):
                if not car.alive:
                    continue
                all_dead = False

                readings = car.get_sensor_readings(track)
                output   = nets[i].activate(readings)
                steer, throttle = output[0], output[1]

                car.update(steer, throttle)

                if track.is_colliding(car.position.x, car.position.y):
                    car.alive = False
                else:
                    _check_checkpoints(car, genome_list[i])
                    genome_list[i].fitness = car.fitness

            # --- Render ---
            current_best = max(g.fitness for g in genome_list)
            best_fitness_ever[0] = max(best_fitness_ever[0], current_best)
            renderer.draw(track, cars, gen, best_fitness_ever[0])
            pygame.display.flip()
            clock_tick(60)

            frame += 1
            if all_dead or frame >= MAX_FRAMES:
                break

    return eval_genomes
